# Site settings
title: Achyut Joshi
tagline: Entrepreneur, Avid Traveller, IITian, Skeptic, Hustler and a lifelong learner
email: achyutj9@gmail.com
description: > # this means to ignore newlines until "baseurl"
  Entrepreneur, Avid Traveller, IITian, Skeptic, Hustler and a lifelong learner. I share my life through this blog.
baseurl: "" # the subpath of your site, e.g. /blog/
 # the base hostname & protocol for your site
twitter_username: achyutjosh1995
twitter:
  username: achyutjosh1995

facebook:
  app_id: 1605837139430627
  admins: ajoshi1995

social:
  name: Achyut Joshi
  links:
    - https://twitter.com/achyutjosh1995
    - https://www.facebook.com/ajoshi1995
    - https://www.linkedin.com/in/achyutjoshi/

paginate: 5
permalink: /:categories/:title
# Build settings
markdown: kramdown
# kramdown :
#   math_engine : mathjax
#highlighter: pygments
aboutPage: true

analytics :
  provider : google
  google :
      tracking_id : 'UA-76699034-1'



# Gems
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
