# Site settings
title: Achyut Joshi 
tagline: Entrepreneur, Avid Traveller, IITian, Skeptic, Hustler and a lifelong learner
email: achyutj9@gmail.com
description: > # this means to ignore newlines until "baseurl"
  Entrepreneur, Avid Traveller, IITian, Skeptic, Hustler and a lifelong learner. I share my life through this blog.
baseurl: "" # the subpath of your site, e.g. /blog/
 # the base hostname & protocol for your site
twitter_username: achyutjosh1995
paginate: 5
permalink: /:categories/:title
# Build settings
markdown: kramdown
#highlighter: pygments
aboutPage: true

analytics :
  provider : google
  google : 
      tracking_id : 'UA-76699034-1'

# Gems
gems: [jekyll-paginate]